apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: simple-web-container
        image: akhiakhi1/simple-web-app   # used Docker Hub image
        ports:
        - containerPort: 3000